version: "3.8"

services:
  backend:
    container_name: backend26
    environment:
      REDIS_HOST: redis
    build: ./example-backend
    ports:
      - 8080:8080
  frontend:
    container_name: frontend26
    build: ./example-frontend
    ports:
      - 5000:5000
  redis:
    container_name: redis-cache26
    image: redis
    restart: unless-stopped
  postgresdb:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_HOST: postgresdb
      POSTGRES_USER: postgresdb
      POSTGRES_PASSWORD: postgresdb
      POSTGRES_DATABASE: postgresdb
