version: "3.8"

services:
  ml-kurkkumopo-backend:
    container_name: ml-kurkkumopo-backend
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
  ml-kurkkumopo-frontend:
    container_name: ml-kurkkumopo--frontend
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
  ml-kurkkumopo-training:
    container_name: ml-kurkkumopo-training
    build: ./ml-kurkkumopo-training
    volumes:
      - model:/src/model
      - images:/src/imgs
      - data:/src/data
volumes:
  model:
  images:
  data:
